version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./data:/app/data
      - ./content:/app/content
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped

# Optional database for persistent storage
# Uncomment if needed
# db:
#   image: postgres:14-alpine
#   container_name: market-intelligence-postgres
#   restart: always
#   ports:
#     - "127.0.0.1:5432:5432"
#   environment:
#     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
#     - POSTGRES_USER=${POSTGRES_USER:-postgres}
#     - POSTGRES_DB=${POSTGRES_DB:-market_intelligence}
#   volumes:
#     - postgres_data:/var/lib/postgresql/data

# Optional monitoring with Prometheus and Grafana
# Uncomment if needed
# prometheus:
#   image: prom/prometheus:latest
#   container_name: market-intelligence-prometheus
#   restart: always
#   ports:
#     - "127.0.0.1:9090:9090"
#   volumes:
#     - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     - prometheus_data:/prometheus

# grafana:
#   image: grafana/grafana:latest
#   container_name: market-intelligence-grafana
#   restart: always
#   ports:
#     - "127.0.0.1:3001:3000"
#   volumes:
#     - grafana_data:/var/lib/grafana
#   depends_on:
#     - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  gcc_net:
    driver: bridge 