name: gcc-business-intelligence
region: nyc
services:
- name: web
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: gunicorn src.deployments.digital_ocean_app:application --workers 2 --timeout 120
  envs:
  - key: ENVIRONMENT
    value: production
    scope: RUN_TIME
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  routes:
  - path: /
static_sites:
- name: reports
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  build_command: echo "No build required for static reports"
  output_dir: reports
  routes:
  - path: /reports 